-- Схема интерьерного бота в общей базе Supabase.
--
-- Почему отдельная схема, а не public: в этом же проекте живут кейсы
-- comp_design_bot. Схема `interior` держит два продукта врозь и заодно прячет
-- таблицы от публичного REST — PostgREST отдаёт наружу только те схемы, что
-- перечислены в настройках API, и `public` там по умолчанию одна.
--
-- Прогонять можно повторно: всё создаётся через IF NOT EXISTS.

CREATE SCHEMA IF NOT EXISTS interior;

-- Никакого доступа анонимам и вошедшим через Supabase Auth: в эту базу ходит
-- только наш бэкенд по строке подключения. Право забирается и у схемы, и у
-- будущих таблиц в ней.
REVOKE ALL ON SCHEMA interior FROM anon, authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA interior REVOKE ALL ON TABLES FROM anon, authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA interior REVOKE ALL ON SEQUENCES FROM anon, authenticated;

CREATE TABLE IF NOT EXISTS interior.schema_meta (
    key   text PRIMARY KEY,
    value text NOT NULL
);

INSERT INTO interior.schema_meta (key, value) VALUES ('schema_version', '1')
ON CONFLICT (key) DO NOTHING;

CREATE TABLE IF NOT EXISTS interior.users (
    -- generated BY DEFAULT, а не ALWAYS: при переносе из SQLite id вставляются
    -- явно, иначе разъедутся все ссылки на пользователя.
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telegram_user_id bigint      NOT NULL UNIQUE,
    username         text,
    first_name       text,
    last_name        text,
    language_code    text,
    created_at       timestamptz NOT NULL,
    updated_at       timestamptz NOT NULL,
    last_seen_at     timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS interior.projects (
    id                 text PRIMARY KEY,
    user_id            bigint      NOT NULL REFERENCES interior.users(id) ON DELETE CASCADE,
    code_name          text        NOT NULL,
    object_type        text,
    area_m2            double precision,
    project_started_on text,
    concept_due_on     text,
    presentation_on    text,
    implementation_on  text,
    created_at         timestamptz NOT NULL,
    updated_at         timestamptz NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_projects_user ON interior.projects (user_id, updated_at DESC);

CREATE TABLE IF NOT EXISTS interior.test_sessions (
    id                  text PRIMARY KEY,
    user_id             bigint      NOT NULL REFERENCES interior.users(id) ON DELETE CASCADE,
    project_id          text        REFERENCES interior.projects(id) ON DELETE CASCADE,
    test_key            text        NOT NULL,
    test_version        text        NOT NULL,
    scoring_version     text        NOT NULL,
    phrase_bank_version text        NOT NULL,
    status              text        NOT NULL CHECK (status IN ('in_progress', 'completed', 'abandoned')),
    current_question_id text,
    started_at          timestamptz NOT NULL,
    updated_at          timestamptz NOT NULL,
    completed_at        timestamptz
);

CREATE INDEX IF NOT EXISTS idx_sessions_user    ON interior.test_sessions (user_id, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_sessions_project ON interior.test_sessions (project_id, updated_at DESC);

CREATE TABLE IF NOT EXISTS interior.session_answers (
    session_id  text        NOT NULL REFERENCES interior.test_sessions(id) ON DELETE CASCADE,
    question_id text        NOT NULL,
    answer      jsonb       NOT NULL,
    answered_at timestamptz NOT NULL,
    PRIMARY KEY (session_id, question_id)
);

CREATE TABLE IF NOT EXISTS interior.test_results (
    id                    text        PRIMARY KEY,
    -- UNIQUE держит защиту от гонки двойного завершения: победитель пишет,
    -- проигравший получает уже записанный результат (см. complete_session).
    session_id            text        NOT NULL UNIQUE REFERENCES interior.test_sessions(id) ON DELETE CASCADE,
    primary_narrative_key text        NOT NULL,
    primary_score         integer     NOT NULL CHECK (primary_score BETWEEN 0 AND 100),
    alternatives          jsonb       NOT NULL,
    confidence            integer     NOT NULL CHECK (confidence BETWEEN 0 AND 100),
    result_text           text        NOT NULL,
    fragment_ids          jsonb       NOT NULL,
    scoring_trace         jsonb       NOT NULL,
    created_at            timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS interior.analytics_events (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    bigint      REFERENCES interior.users(id) ON DELETE SET NULL,
    session_id text        REFERENCES interior.test_sessions(id) ON DELETE SET NULL,
    event_name text        NOT NULL,
    payload    jsonb       NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_events_name_time ON interior.analytics_events (event_name, created_at DESC);
